interface IPlayer {
  name: string
  mvp: number
  finals_mvp: number
  age: number | string
  born: string
  current_team: string
  dpoy?: number
  mip?: number
  roy?: number
  jersey_number: number
  nacionality: string
  draft_team: string
  draft_year: number
  draft_position: string
  height: string
  position: string
  championship: number
  description: string
  img: string
}

export const PLAYERS: IPlayer[] = [
  {
    name: 'Ja Morant',
    mvp: 0,
    jersey_number: 12,
    finals_mvp: 0,
    age: 23,
    born: '10/08/1999',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Memphis Grizzlies',
    nacionality: 'EUA',
    draft_position: '2º',
    draft_year: 2019,
    position: 'Armador',
    height: '1,88',
    championship: 0,
    description: 'Temetrius Jamel "Ja" Morant é um jogador de basquete profissional que joga no Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário na Universidade Estadual de Murray e foi selecionado pelos Grizzlies como a segunda escolha geral no Draft da NBA de 2019.',
    img: 'https://s2.glbimg.com/ckgOBEaj6knpG3rRN1HoH3Mh65s=/0x53:1826x1636/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2021/N/i/TBNRUmTgqE9qiJHA8Bcw/gettyimages-1236700390.jpg'
  },
  {
    name: 'Jaren Jackson Jr',
    mvp: 0,
    jersey_number: 13,
    finals_mvp: 0,
    age: 23,
    born: '15/09/1999',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Memphis Grizzlies',
    nacionality: 'EUA',
    draft_position: '4º',
    draft_year: 2018,
    position: 'Ala-pivô',
    height: '2,08',
    championship: 0,
    description: 'Jaren Walter Jackson Jr. é um basquetebolista americano que atualmente joga pelo Memphis Grizzlies, time da NBA. Em 21 de Junho de 2018, foi draftado na 4ª escolha pelo Memphis Grizzlies. No fim da sua primeira temporada, foi selecionada para o Primeiro Time do NBA All-Rookie Team',
    img: 'https://nba.nbcsports.com/wp-content/uploads/sites/12/2022/07/GettyImages-1240571379-e1656675986729.jpg?w=1024'
  },
  {
    name: 'Desmond Bane',
    mvp: 0,
    jersey_number: 22,
    finals_mvp: 0,
    age: 24,
    born: '25/07/1998',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Boston Celticts',
    nacionality: 'EUA',
    draft_position: '30º',
    draft_year: 2020,
    position: 'Ala-armador',
    height: '1,96',
    championship: 0,
    description: 'Desmond Michael Bane é um basquetebolista profissional norte-americano, que joga pelo time Memphis Grizzlies da National Basketball Association.',
    img: 'https://gray-wbko-prod.cdn.arcpublishing.com/resizer/NlrOWjokHrO5hOT8CN3jiFsG-m8=/1200x675/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/7EWELJF3FVJVJGFD5TPYN7DA6I.jpg'
  },
  {
    name: 'Dillon Brooks',
    mvp: 0,
    jersey_number: 24,
    finals_mvp: 0,
    age: 27,
    born: '22/01/1996',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Houston Rockets',
    nacionality: 'Canada',
    draft_position: '45º',
    draft_year: 2017,
    position: 'Ala-armador',
    height: '1,98',
    championship: 0,
    description: 'Dillon Brooks é um jogador de basquete profissional canadense do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário pelo Oregon Ducks, onde foi nomeado um consenso do segundo time All-American e ganhou as honras de jogador do ano da conferência no Pac-12 em 2017.',
    img: 'https://d1dglpr230r57l.cloudfront.net/images/xlarge/USATSI_19588682_168390303_lowres.jpg'
  },
  {
    name: 'Tyus Jones',
    mvp: 0,
    jersey_number: 21,
    finals_mvp: 0,
    age: 26,
    born: '10/05/1996',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Cleveland Cavaliers',
    nacionality: 'EUA',
    draft_position: '24º',
    draft_year: 2015,
    position: 'Armador',
    height: '1,88',
    championship: 0,
    description: 'Tyus Jones é um jogador norte-americano de basquete profissional que atualmente joga pelo Memphis Grizzlies, disputando a National Basketball Association. Foi draftado em 2015 na primeira rodada pelo Cleveland Cavaliers.',
    img: 'https://gray-kait-prod.cdn.arcpublishing.com/resizer/6uZRWkBOy10ynJdPMtl_G66pkdo=/1200x675/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/GWILTTPARVI7LEVXV2V2RJCW4U.jpg'
  },
  {
    name: 'Steven Adams',
    mvp: 0,
    jersey_number: 4,
    finals_mvp: 0,
    age: 29,
    born: '20/07/1993',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Oklahoma City Thunder',
    nacionality: 'Nova Zelândia',
    draft_position: '12º',
    draft_year: 2013,
    position: 'Pivô',
    height: '2,11',
    championship: 0,
    description: 'Steven Funaki Adams é um jogador de basquetebol profissional neozelandês que joga atualmente pelo Memphis Grizzlies na NBA. Depois de jogar basquetebol universitário pelo Pittsburgh Panthers, ele foi considerado um dos maiores talentos internacionais para a NBA.',
    img: 'https://cdn.theathletic.com/app/uploads/2022/10/01171555/USATSI_19122533-1024x683.jpg'
  },
  {
    name: 'Santi Aldama',
    mvp: 0,
    jersey_number: 7,
    finals_mvp: 0,
    age: 22,
    born: '10/01/2001',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Utah Jazz',
    nacionality: 'Espanha',
    draft_position: '30º',
    draft_year: 2021,
    position: 'Ala-pivô',
    height: '2,13',
    championship: 0,
    description: 'Santiago "Santi" Aldama Toledo é um jogador espanhol de basquete profissional que atualmente joga no Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário pela Universidade de Loyola e foi selecionado pelo Utah Jazz como a 30º escolha geral no draft da NBA de 2021.',
    img: 'https://gray-kait-prod.cdn.arcpublishing.com/resizer/-0Pqu1Y7NN0kk1slZ-DNRcNQGjs=/1200x675/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/3VDZFMW7AFLXHPEL2MXQMSSKTA.jpg'
  },
  {
    name: 'Brandon Clarke',
    mvp: 0,
    jersey_number: 15,
    finals_mvp: 0,
    age: 26,
    born: '19/09/1996',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Oklahoma City Thunder',
    nacionality: 'Canada',
    draft_position: '21º',
    draft_year: 2019,
    position: 'Ala-pivô',
    height: '2,03',
    championship: 0,
    description: 'Brandon Clarke é um canadense jogador de basquete profissional do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário na Universidade Estadual de San Jose e na Universidade de Gonzaga e foi selecionado pelo Oklahoma City Thunder como a 21º escolha geral no Draft da NBA de 2019.',
    img: 'https://media.bleacherreport.com/image/upload/c_fill,g_faces,w_3800,h_2000,q_95/v1665959573/teivdhp2cyloe9nndior.jpg'
  },
  {
    name: 'John Konchar',
    mvp: 0,
    jersey_number: 12,
    finals_mvp: 0,
    age: 46,
    born: '22/04/1996',
    current_team: 'Memphis Grizzlies',
    draft_team: '',
    nacionality: 'Canada',
    draft_position: 'Konchar não foi draftado',
    draft_year: 2019,
    position: 'Ala-armador',
    height: '1,96',
    championship: 0,
    description: 'John Konchar é um jogador de basquete profissional americano do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário no Purdue Fort Wayne Mastodons.',
    img: 'https://nba.nbcsports.com/wp-content/uploads/sites/12/2022/07/GettyImages-1391319840-e1657222601922.jpg?w=778'
  },
  {
    name: 'Xavier Tillman Sr',
    mvp: 0,
    jersey_number: 2,
    finals_mvp: 0,
    age: 24,
    born: '12/01/1999',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Sacramento Kings',
    nacionality: 'EUA',
    draft_position: '35º',
    draft_year: 2020,
    position: 'Ala-pivô',
    height: '2,01',
    championship: 0,
    description: 'Xavier Justis Tillman Sr. é um jogador de basquete profissional americano do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário pelo Michigan State Spartans.',
    img: 'https://s.yimg.com/ny/api/res/1.2/mQE.0DbY4QNtY4UWS2b1bg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTQyNw--/https://media.zenfs.com/en/the-commercial-appeal/aeac634c2ddbf9ecb57ccd404f43e34d'
  },
  {
    name: 'Ziare Williams',
    mvp: 0,
    jersey_number: 8,
    finals_mvp: 0,
    age: 21,
    born: '12/09/2001',
    current_team: 'Memphis Grizzlies',
    draft_team: 'New Orleans Pelicans',
    nacionality: 'EUA',
    draft_position: '10º',
    draft_year: 2021,
    position: 'Ala-armador',
    height: '2,06',
    championship: 0,
    description: 'Ziaire Williams é um jogador norte-americano de basquete profissional que atualmente joga no Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário pela Universidade de Stanford e foi selecionado pelo New Orleans Pelicans como a 10º escolha geral no draft da NBA de 2021.',
    img: 'https://therookiewire.usatoday.com/wp-content/uploads/sites/12/2022/02/154c3feeb1924e00b671962a21e45dd6.jpg?w=1000&h=600&crop=1'
  },
  {
    name: 'David Roddy',
    mvp: 0,
    jersey_number: 27,
    finals_mvp: 0,
    age: 22,
    born: '27/04/2001',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Memphis Grizzlies',
    nacionality: 'EUA',
    draft_position: '23º',
    draft_year: 2022,
    position: 'Ala-pivô',
    height: '1,93',
    championship: 0,
    description: 'David Michael Roddy é um jogador de basquete profissional americano do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário no Colorado State Rams. No colégio, Roddy jogou basquete, futebol americano e atletismo, recebendo ofertas de bolsas da Divisão I para os dois primeiros.',
    img: 'https://images2.minutemediacdn.com/image/fetch/w_2000,h_2000,c_fit/https%3A%2F%2Fbealestreetbears.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2018%2F08%2F1430468696.jpeg'
  },
  {
    name: 'Jake Laravia',
    mvp: 0,
    jersey_number: 3,
    finals_mvp: 0,
    age: 21,
    born: '03/11/2001',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Minnesota Timberwolves',
    nacionality: 'EUA',
    draft_position: '19º',
    draft_year: 2022,
    position: 'Ala-pivô',
    height: '2,01',
    championship: 0,
    description: 'Jacob Glen LaRavia é um jogador de basquete profissional americano do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário no Indiana State Sycamores e no Wake Forest Demon Deacons.',
    img: 'https://bealestreetbears.com/wp-content/uploads/getty-images/2018/08/1408939210.jpeg'
  },
  {
    name: 'Kenneth Lofton Jr',
    mvp: 0,
    jersey_number: 6,
    finals_mvp: 0,
    age: 20,
    born: '14/08/2002',
    current_team: 'Memphis Grizzlies',
    draft_team: '',
    nacionality: 'EUA',
    draft_position: 'Kenneth Lofton Jr não foi draftado',
    draft_year: 2022,
    position: 'Ala-pivô',
    height: '2,01',
    championship: 0,
    description: 'Kenneth Wayne Lofton Jr. é um jogador de basquete profissional americano do Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário no Louisiana Tech Bulldogs.',
    img: 'https://i.ytimg.com/vi/_MATf3lX0Qc/maxresdefault.jpg'
  },
  {
    name: 'Luke Kennard',
    mvp: 0,
    jersey_number: 10,
    finals_mvp: 0,
    age: 26,
    born: '24/06/1996',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Detroit Pistons',
    nacionality: 'EUA',
    draft_position: '12º',
    draft_year: 2017,
    position: 'Ala-armador',
    height: '1,96',
    championship: 0,
    description: 'Luke Douglas Kennard é um basquetebolista profissional americano que atualmente joga pelo Memphis Grizzlies da National Basketball Association. Ele jogou basquete universitário na Universidade de Duke e foi selecionado pelo Detroit Pistons com a 12° escolha geral no Draft da NBA de 2017',
    img: 'https://a.espncdn.com/media/motion/2023/0324/ss_20230324_222916306_2229893/ss_20230324_222916306_2229893.jpg'
  },
  {
    name: 'Lebron James',
    mvp: 4,
    jersey_number: 6,
    finals_mvp: 4,
    age: 38,
    born: '30/12/1984',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Cleveland Cavaliers',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 2003,
    position: 'Ala-pivô',
    height: '2,06',
    championship: 4,
    description: 'LeBron Raymone James é um basquetebolista norte-americano que atua como ala pelo Los Angeles Lakers. Apelidado de King James, é amplamente reconhecido como um dos maiores jogadores de basquetebol de todos os tempos, ocupando a segunda posição na lista divulgada pela ESPN em 2020, atrás apenas de Michael Jordan.',
    img: 'https://www.si.com/.image/t_share/MTk3MTkzMTIxMTExNDgzNDc1/lebron-james.jpg'
  },
  {
    name: 'Anthony Davis',
    mvp: 0,
    jersey_number: 3,
    finals_mvp: 0,
    age: 30,
    born: '11/04/1993',
    current_team: 'Los Angeles Lakers',
    draft_team: 'New Orleans Pelicans',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 2012,
    position: 'Ala-pivô',
    height: '2,08',
    championship: 1,
    description: 'Anthony Marshon Davis Jr. é um basquetebolista estadunidense que atua como ala-pivô ou pivô. Atualmente defende o Los Angeles Lakers na NBA.',
    img: 'https://cdn.nba.com/manage/2023/04/GettyImages-1252095636-scaled-e1682272710227.jpg'
  },
  {
    name: 'D Angelo Russell',
    mvp: 0,
    jersey_number: 1,
    finals_mvp: 0,
    age: 27,
    born: '23/02/1996',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Los Angeles Lakers',
    nacionality: 'EUA',
    draft_position: '2º',
    draft_year: 2015,
    position: 'Armador',
    height: '1,93',
    championship: 0,
    description: 'D Angelo Danté Russell é um jogador norte-americano de basquete profissional que atualmente joga pelo Los Angeles Lakers na National Basketball Association.',
    img: 'https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2NTEwOTcxMDUxNjQ4MTUw/usatsi_20007072_168396005_lowres-1.jpg'
  },
  {
    name: 'Austin Reaves',
    mvp: 0,
    jersey_number: 15,
    finals_mvp: 0,
    age: 24,
    born: '29/05/1998',
    current_team: 'Los Angeles Lakers',
    draft_team: '',
    nacionality: 'EUA',
    draft_position: 'Aunstin Reaves não foi draftado',
    draft_year: 2021,
    position: 'Ala',
    height: '1,96',
    championship: 0,
    description: 'Austin Reaves é um jogador norte-americano de basquete profissional que atualmente joga pelo Los Angeles Lakers na National Basketball Association.',
    img: 'https://media.bleacherreport.com/image/upload/c_fill,g_faces,w_3800,h_2000,q_95/v1679329193/lbqyc9zo4pqywzaqykeg.jpg'
  },
  {
    name: 'Trae Young',
    mvp: 0,
    jersey_number: 11,
    finals_mvp: 0,
    age: 24,
    born: '19/09/1998',
    current_team: 'Atlanta Hawks',
    draft_team: 'Dallas Mavericks',
    nacionality: 'EUA',
    draft_position: '5º',
    draft_year: 2018,
    position: 'Armador',
    height: '1,85',
    championship: 0,
    description: 'Rayford Trae Young é um jogador norte-americano de basquete profissional que atualmente joga no Atlanta Hawks da National Basketball Association.',
    img: 'https://cdn.nba.com/teams/uploads/sites/1610612737/2023/04/Traehighlight-1.jpg'
  },
  {
    name: 'Luka Doncic',
    mvp: 0,
    jersey_number: 77,
    finals_mvp: 0,
    age: 24,
    born: '28/02/1999',
    current_team: 'Dallas Mavericks',
    draft_team: 'Atlanta Hawks',
    nacionality: 'Eslovênia',
    draft_position: '3º',
    draft_year: 2018,
    position: 'Armador',
    height: '2,01',
    championship: 0,
    description: 'Luka Dončić é um jogador de basquete esloveno, que joga atualmente no Dallas Mavericks, na NBA. Foi escolhido pelo Atlanta Hawks na 3ª escolha no Draft da NBA de 2018, em seguida trocado para os Dallas Mavericks por Trae Young',
    img: 'https://cdn.nba.com/teams/uploads/sites/1610612737/2023/04/Traehighlight-1.jpg'
  },
  {
    name: 'Michael Jordan',
    mvp: 5,
    jersey_number: 23,
    finals_mvp: 6,
    age: 60,
    born: '17/02/1963',
    current_team: 'Chicago Bulls',
    draft_team: 'Chicago Bulls',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 1984,
    position: 'Ala-armador',
    height: '1,98',
    championship: 6,
    description: 'Michael Jeffrey Jordan é um empresário e ex-basquetebolista estadunidense que atuava como ala-armador. É considerado por muitos como o melhor jogador de basquete de todos os tempos e por muitos como um dos mais importantes desportistas masculinos da história.',
    img: 'https://imageio.forbes.com/specials-images/imageserve/5d6586c068cb0a0008c08f54/Michael-Jordan/0x0.jpg?format=jpg&height=1963&width=1963'
  },
  {
    name: 'Kobe Bryant',
    mvp: 1,
    jersey_number: 24,
    finals_mvp: 2,
    age: 'Facelimento em 26/01/2020',
    born: '23/08/1978',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Charlote Hornets',
    nacionality: 'EUA',
    draft_position: '13º',
    draft_year: 1996,
    position: 'Ala-armador',
    height: '1,98',
    championship: 5,
    description: 'Kobe Bean Bryant foi um jogador profissional de basquetebol estadunidense. Jogou toda sua carreira como ala-armador no Los Angeles Lakers da National Basketball Association.',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kobe_Bryant_2014.jpg/640px-Kobe_Bryant_2014.jpg'
  },
  {
    name: 'Shaq O Neill',
    mvp: 1,
    jersey_number: 34,
    finals_mvp: 3,
    age: 51,
    born: '06/04/1972',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Orlando Magic',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 1992,
    position: 'Pivô',
    height: '2,16',
    championship: 4,
    description: 'Shaquille Rashaun O Neal é um empresário, comentarista esportivo e ex-basquetebolista norte-americano que atuava como pivô. "Shaq", como ficou conhecido, é frequentemente descrito por especialistas e entusiastas do basquete como um dos jogadores mais dominantes da história da National Basketball Association.',
    img: 'https://static.wikia.nocookie.net/nba-basketball/images/b/b0/Shaquille_O%27Neal.jpeg/revision/latest/scale-to-width-down/800?cb=20160709122018'
  },
  {
    name: 'Tony Parker',
    mvp: 1,
    jersey_number: 9,
    finals_mvp: 1,
    age: 40,
    born: '17/05/1982',
    current_team: 'San Antonio Spurs',
    draft_team: 'San Antonio Spurs',
    nacionality: 'França',
    draft_position: '28º',
    draft_year: 2001,
    position: 'Armador',
    height: '1,88',
    championship: 4,
    description: 'William Anthony "Tony" Parker Jr é um ex-jogador de basquetebol francês, nascido na Bélgica. Em sua carreira na NBA, Parker jogou pelo San Antonio Spurs, onde é um dos maiores jogadores da história da franquia e jogou sua última temporada pelo Charlotte Hornets',
    img: 'https://library.sportingnews.com/styles/crop_style_16_9_mobile_2x/s3/2021-08/parkertony49gettyus_1fwnxv4jsmdz61imxq98acdfku.jpg?itok=owxTMdRj'
  },
  {
    name: 'Tim Duncan',
    mvp: 2,
    jersey_number: 21,
    finals_mvp: 3,
    age: 47,
    born: '25/04/1976',
    current_team: 'San Antonio Spurs',
    draft_team: 'San Antonio Spurs',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 1997,
    position: 'Ala-pivô',
    height: '2,11',
    championship: 5,
    description: 'Timothy "Tim" Theodore Duncan é um ex-basquetebolista e treinador norte-americano que jogava como ala-pivô na National Basketball Association pelo San Antonio Spurs. Duncan é considerado o maior ala-pivô da história da NBA.',
    img: 'https://cdn.vox-cdn.com/thumbor/AJ761RZ7j5AmX_jw2r7VyKzFGtg=/0x0:2040x3072/1200x800/filters:focal(491x915:817x1241)/cdn.vox-cdn.com/uploads/chorus_image/image/70433509/72317068.0.jpg'
  },
  {
    name: 'Giannis Antetokounmpo',
    mvp: 2,
    jersey_number: 34,
    finals_mvp: 1,
    age: 28,
    born: '06/12/1994',
    current_team: 'Milwaukee Bucks',
    draft_team: 'Milwaukee Bucks',
    nacionality: 'Grecia',
    draft_position: '15º',
    draft_year: 2013,
    position: 'Ala-pivô',
    height: '2,13',
    championship: 1,
    description: 'Giannis Sina Ugo Antetokounmpo é um jogador greco-nigeriano profissional de basquetebol que atualmente joga pelo Milwaukee Bucks da National Basketball Association. Nascido na Grécia de pais nigerianos, Antetokounmpo começou a jogar basquete nas equipes juvenis do Filathlitikos em Atenas. ',
    img: 'https://i.insider.com/640907fa1bbdd30018ed8aec?width=1136&format=jpeg'
  },
  {
    name: 'Brook Lopez',
    mvp: 0,
    jersey_number: 11,
    finals_mvp: 0,
    age: 35,
    born: '01/04/1988',
    current_team: 'Milwaukee Bucks',
    draft_team: 'New Jersey Nets (Atual Brooklyn Nets)',
    nacionality: 'EUA',
    draft_position: '10º',
    draft_year: 2008,
    position: 'Pivô',
    height: '2,16',
    championship: 1,
    description: 'Brook Robert Lopez é um jogador norte-americano de basquete profissional que atualmente joga no Milwaukee Bucks da National Basketball Association. Ele jogou dois anos de basquete universitário na Universidade de Stanford e foi selecionado pelo New Jersey Nets como a décima escolha geral no draft da NBA de 2008.',
    img: 'https://i.ytimg.com/vi/-Nm36QnRhFY/maxresdefault.jpg'
  },
  {
    name: 'John Collins',
    mvp: 0,
    jersey_number: 20,
    finals_mvp: 0,
    age: 25,
    born: '23/09/1997',
    current_team: 'Atlanta Hawks',
    draft_team: 'Atlanta Hawks',
    nacionality: 'EUA',
    draft_position: '19º',
    draft_year: 2017,
    position: 'Ala',
    height: '2,06',
    championship: 0,
    description: 'John Martin Collins III é um jogador norte-americano de basquete profissional que atualmente joga pelo Atlanta Hawks da National Basketball Association. Ele jogou basquete universitário na Universidade Wake Forest e foi selecionado pelos Hawks como a 19ª escolha geral no Draft da NBA de 2017',
    img: 'https://www.si.com/.image/t_share/MTg0NTg3MTM4NDI2MjE3NTky/usatsi_16953485.jpg'
  },
  {
    name: 'Dejounte Murray',
    mvp: 0,
    jersey_number: 5,
    finals_mvp: 0,
    age: 26,
    born: '19/09/1996',
    current_team: 'Atlanta Hawks',
    draft_team: 'San Antonio Spurs',
    nacionality: 'EUA',
    draft_position: '29º',
    draft_year: 2016,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Dejounte Dashaun Murray é um jogador norte-americano de basquete profissional que atualmente joga no Atlanta Hawks na National Basketball Association. Ele jogou basquete universitário na Universidade de Washington e foi selecionado pelo San Antonio Spurs como a 29ª escolha geral no draft da NBA de 2016',
    img: 'https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2022/12/1200/675/Dejounte-Murray.jpg?ve=1&tl=1'
  },
  {
    name: 'Kyle Anderson',
    mvp: 0,
    jersey_number: 5,
    finals_mvp: 0,
    age: 29,
    born: '20/09/1993',
    current_team: 'Minnesota Timberwolves',
    draft_team: 'San Antonio Spurs',
    nacionality: 'EUA',
    draft_position: '30º',
    draft_year: 2014,
    position: 'Ala-pivô',
    height: '2,06',
    championship: 0,
    description: 'Kyle F. Anderson é um jogador de basquetebol profissional norte-americano que atualmente joga pelo Minnesota Timberwolves na NBA. Foi selecionado pelos Spurs na primeira rodada do Draft da NBA de 2014 como a 30ª escolha geral',
    img: 'https://cdn.vox-cdn.com/thumbor/_hfUxyuNQJhIuaD1YsTKNjuLI-U=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/24191309/1243977624.jpg'
  },
  {
    name: 'De Anthony Melton',
    mvp: 0,
    jersey_number: 8,
    finals_mvp: 0,
    age: 24,
    born: '28/05/1998',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Houston Rockets',
    nacionality: 'EUA',
    draft_position: '46º',
    draft_year: 2018,
    position: 'Armador',
    height: '1,88',
    championship: 0,
    description: 'De Anthony Melton é um jogador norte-americano de basquete profissional que atualmente joga no Philadelphia 76ers da National Basketball Association. Ele jogou basquete universitário pela USC e foi selecionado pelo Houston Rockets como a 46ª escolha no draft da NBA de 2018.',
    img: 'https://s.yimg.com/ny/api/res/1.2/lcT3BKDoMUSdhX3Qn5F1tw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTQyNw--/https://media.zenfs.com/en/sixers_wire_usa_today_sports_articles_847/4ad0c41ab04c99c1e6e7a43380bdc801'
  },
  {
    name: 'Tyrese Maxey',
    mvp: 0,
    jersey_number: 0,
    finals_mvp: 0,
    age: 22,
    born: '04/11/2000',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Philadelphia 76ers',
    nacionality: 'EUA',
    draft_position: '21º',
    draft_year: 2020,
    position: 'Armador',
    height: '1,88',
    championship: 0,
    description: 'Tyrese Maxey é um jogador norte-americano de basquete profissional que atualmente joga no Philadelphia 76ers da National Basketball Association. Ele jogou basquete universitário no Kentucky Wildcats e foi selecionado pelos 76ers como a 21ª escolha geral no draft da NBA de 2020.',
    img: 'https://cdn.nba.com/teams/legacy/www.nba.com/sixers/sites/sixers/files/getty-images-1238023470.jpg'
  },
  {
    name: 'Tobias Harris',
    mvp: 0,
    jersey_number: 12,
    finals_mvp: 0,
    age: 30,
    born: '15/07/1992',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Charlote Bobacats (Atual Charlote Hornets)',
    nacionality: 'EUA',
    draft_position: '19º',
    draft_year: 2011,
    position: 'Ala-pivô',
    height: '2,01',
    championship: 0,
    description: 'Tobias John Harris é um jogador norte-americano de basquete profissional que atualmente joga pelo Philadelphia 76ers da National Basketball Association. Ele jogou basquete universitário pela Universidade do Tennessee e foi selecionado pelo Charlotte Bobcats como a 19ª escolha geral no draft da NBA de 2011',
    img: 'https://s.yimg.com/ny/api/res/1.2/nwD.AibZof55oJI5eZHkUg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTY3NA--/https://media.zenfs.com/en/sixers_wire_usa_today_sports_articles_847/03313b81cc036cd01b257dae8c5d7d4f'
  },
  {
    name: 'Shake Milton',
    mvp: 0,
    jersey_number: 18,
    finals_mvp: 0,
    age: 26,
    born: '26/09/1996',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Dallas Mavericks',
    nacionality: 'EUA',
    draft_position: '54º',
    draft_year: 2018,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Malik Benjamin "Shake" Milton é um jogador norte-americano de basquete profissional que joga no Philadelphia 76ers da National Basketball Association.',
    img: 'https://sportshub.cbsistatic.com/i/r/2020/03/02/e3a6e6d2-de88-4329-a4a0-8203333e4797/thumbnail/1200x675/2f88847e7aa99226315045b6a00a02a7/shake-milton.jpg'
  },
  {
    name: 'Joel Embiid',
    mvp: 0,
    jersey_number: 21,
    finals_mvp: 0,
    age: 29,
    born: '16/04/1994',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Philadelphia 76ers',
    nacionality: 'Camarões',
    draft_position: '3º',
    draft_year: 2014,
    position: 'Pivô',
    height: '2,13',
    championship: 0,
    description: 'Joel Hans Embiid é um jogador camaronês de basquete profissional que atualmente joga no Philadelphia 76ers da National Basketball Association. Após um ano de basquete universitário na Universidade do Kansas, ele foi selecionado pelos 76ers com a terceira escolha geral do Draft de 2014.',
    img: 'https://library.sportingnews.com/styles/crop_style_16_9_mobile_2x/s3/2023-04/Joel%20Embiid%20041923.jpg?h=920929c4&itok=tEX0vja7'
  },
  {
    name: 'James Harden',
    mvp: 1,
    jersey_number: 1,
    finals_mvp: 0,
    age: 33,
    born: '26/08/1989',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Ocklahoma City Thunder',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 2014,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'James Edward Harden Jr. é um jogador norte-americano de basquetebol profissional que atualmente joga pelo Philadelphia 76ers da NBA. Ele jogou basquete universitário na Universidade Estadual do Arizona, onde foi nomeado para a Primeira-Equipe All-American e recebeu o prêmio de Jogador do Ano da Pac-10 em 2009.',
    img: 'https://d1dglpr230r57l.cloudfront.net/images/xlarge/USATSI_19903527_168390303_lowres.jpg'
  },
  {
    name: 'P. J. Tucker',
    mvp: 1,
    jersey_number: 17,
    finals_mvp: 0,
    age: 37,
    born: '05/05/1985',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Toronto Raptors',
    nacionality: 'EUA',
    draft_position: '35º',
    draft_year: 2006,
    position: 'Ala-pivô',
    height: '1,96',
    championship: 0,
    description: 'Anthony Leon "P. J." Tucker Jr. é um jogador norte-americano de basquete profissional que atualmente joga no Philadelphia 76ers da National Basketball Association. Ele frequentou a Universidade do Texas em Austin e foi selecionado pelo Toronto Raptors como a 35ª escolha geral no draft da NBA de 2006.',
    img: 'https://thesixersense.com/wp-content/uploads/imagn-images/2017/07/19122294.jpeg'
  },
  {
    name: 'Allen Iverson',
    mvp: 1,
    jersey_number: 3,
    finals_mvp: 0,
    age: 47,
    born: '07/07/1975',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Philadelphia 76ers',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 1996,
    position: 'Armador',
    height: '1,83',
    championship: 0,
    description: 'Allen Ezail Iverson, apelidado de "The Answer", é um ex-jogador norte-americano de basquete profissional que atuava como Ala-armador/Armador. Considerado um dos melhores jogadores da década de 2000 da NBA. Allen Iverson entrou na liga em 1996 e em pouco tempo se tornou um de seus principais jogadores.',
    img: 'https://i.ytimg.com/vi/2REkZG-dhHc/maxresdefault.jpg'
  },
  {
    name: 'Allen Iverson',
    mvp: 0,
    jersey_number: 15,
    finals_mvp: 0,
    age: 46,
    born: '26/01/1977',
    current_team: 'Philadelphia 76ers',
    draft_team: 'Golden State Warriors',
    nacionality: 'EUA',
    draft_position: '5º',
    draft_year: 1998,
    position: 'Ala-armador',
    height: '1,98',
    championship: 0,
    description: 'Vincent Lamar Carter Jr. é um ex-jogador americano de basquete profissional. Carter é o único jogador da história da NBA a jogar 22 temporadas consecutivas e foi o primeiro jogador a jogar em quatro décadas diferentes. Ele é amplamente considerado como o maior Dunker de todos os tempos.',
    img: 'https://images2.minutemediacdn.com/image/fetch/w_2000,h_2000,c_fit/https%3A%2F%2Fraptorsrapture.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F07%2F470135913-toronto-raptors-v-houston-rockets.jpg.jpg'
  },
  {
    name: 'Reggie Miller',
    mvp: 0,
    jersey_number: 31,
    finals_mvp: 0,
    age: 57,
    born: '24/08/1965',
    current_team: 'Indiana Pacers',
    draft_team: 'Indiana Pacers',
    nacionality: 'EUA',
    draft_position: '11º',
    draft_year: 1987,
    position: 'Ala-armador',
    height: '2,01',
    championship: 0,
    description: 'Reginald "Reggie" Wayne Miller é um ex-basquetebolista estadunidense que atuava como ala-armador. Jogou toda a sua carreira de 18 anos na National Basketball Association com o Indiana Pacers.',
    img: 'https://www.nbamaniacs.com/wp-content/uploads/2020/04/GettyImages-2926440-768x545.jpg'
  },
  {
    name: 'Chris Paul',
    mvp: 0,
    jersey_number: 31,
    finals_mvp: 0,
    age: 37,
    born: '06/05/1985',
    current_team: 'Phoenix Suns',
    draft_team: 'New Orleans Hornets (Atual New Orleans Pelicans)',
    nacionality: 'EUA',
    draft_position: '4º',
    draft_year: 2005,
    position: 'Ala-armador',
    height: '1,84',
    championship: 0,
    description: 'Christopher Emmanuel Paul é um jogador profissional de basquetebol estadunidense que atualmente defende o Phoenix Suns da NBA. Em 2021, ele foi homenageado como um dos 75 maiores jogadores da história da NBA.',
    img: 'https://cdn.nba.com/manage/2023/02/GettyImages-1247209861-1568x1026.jpg'
  },
  {
    name: 'Paul George',
    mvp: 0,
    jersey_number: 13,
    finals_mvp: 0,
    age: 32,
    born: '02/05/1990',
    current_team: 'Los Angeles Clippers',
    draft_team: 'Indiana Pacers',
    nacionality: 'EUA',
    draft_position: '10º',
    draft_year: 2005,
    position: 'Ala-armador',
    height: '2,03',
    championship: 0,
    description: 'Paul Clifton Anthony George é um jogador norte-americano de basquete profissional que atua como ala. Atualmente joga pelo Los Angeles Clippers na NBA.',
    img: 'https://mobile-img.lpcdn.ca/lpca/924x/r3996/669822ea-3b20-11eb-a88b-02fe89184577.jpg'
  },
  {
    name: 'Kawhi Leonard',
    mvp: 0,
    jersey_number: 2,
    finals_mvp: 2,
    age: 31,
    born: '29/06/1991',
    current_team: 'Los Angeles Clippers',
    draft_team: 'Indiana Pacers',
    nacionality: 'EUA',
    draft_position: '15º',
    draft_year: 2011,
    position: 'Ala-armador',
    height: '2,01',
    championship: 2,
    description: 'Kawhi Anthony Leonard é um jogador norte-americano de basquete profissional que atua como ala. Atualmente defende o Los Angeles Clippers na NBA. Kawhi jogou duas temporadas no basquete universitário pela Universidade Estadual de San Diego.',
    img: 'https://ca-times.brightspotcdn.com/dims4/default/eea143a/2147483647/strip/false/crop/3882x2184+0+0/resize/1486x836!/quality/80/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2Fa5%2F62%2Fb29a1da047689f1bdde6251930f8%2Fclippers-basketball-83404.jpg'
  },
  {
    name: 'Kyrie Irving',
    mvp: 0,
    jersey_number: 2,
    finals_mvp: 0,
    age: 31,
    born: '23/03/1992',
    current_team: 'Dallas Mavericks',
    draft_team: 'Cleveland Cavaliers',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 2011,
    position: 'Armador',
    height: '1,88',
    championship: 1,
    description: 'Kyrie Andrew Irving é um jogador norte-americano, nascido na Austrália, de basquete profissional que atua como armador e atualmente joga pelo Dallas Mavericks na NBA. Irving jogou basquete universitário no Duke Blue Devils antes de ingressar na NBA em 2011',
    img: 'https://library.sportingnews.com/2023-02/nba-plain--4267e7b9-3c4c-44aa-b044-20f9356cd14b.png'
  },
  {
    name: 'Mikal Bridges',
    mvp: 0,
    jersey_number: 1,
    finals_mvp: 0,
    age: 26,
    born: '30/08/1996',
    current_team: 'Brooklyn Nets',
    draft_team: 'Philadelphia 76ers',
    nacionality: 'EUA',
    draft_position: '10º',
    draft_year: 2018,
    position: 'Ala-armador',
    height: '1,88',
    championship: 0,
    description: 'Mikal Bridges é um jogador norte-americano de basquete profissional que atualmente joga no Brooklyn Nets da National Basketball Association. Ele jogou basquete universitário por Villanova e venceu os títulos nacionais em 2016 e 2018.',
    img: 'https://cdn.vox-cdn.com/thumbor/vnx_F_yveaiUbvQVw2nWnR2NfSM=/0x260:2871x4184/1200x800/filters:focal(1450x561:1908x1019)/cdn.vox-cdn.com/uploads/chorus_image/image/72144135/1479215330.0.jpg'
  },
  {
    name: 'Kevin Durant',
    mvp: 1,
    jersey_number: 35,
    finals_mvp: 2,
    age: 34,
    born: '29/09/1988',
    current_team: 'Phonix Suns',
    draft_team: 'Seattle SuperSonics (Atual Ocklahoma City Thunder)',
    nacionality: 'EUA',
    draft_position: '2º',
    draft_year: 2007,
    position: 'Ala-pivô',
    height: '2,08',
    championship: 2,
    description: 'Kevin Wayne Durant é um basquetebolista norte-americano que atua como ala. Atualmente joga no Phoenix Suns, da National Basketball Association. Durant é amplamente considerado como um dos maiores jogadores de todos os tempos.',
    img: 'https://media.cnn.com/api/v1/images/stellar/prod/230309084607-kevin-durant-file-030323.jpg?c=3x2'
  },
  {
    name: 'Reggie Bullock',
    mvp: 0,
    jersey_number: 25,
    finals_mvp: 0,
    age: 32,
    born: '16/04/1991',
    current_team: 'Dallas Mavericks',
    draft_team: 'Los Angeles Clippers',
    nacionality: 'EUA',
    draft_position: '25º',
    draft_year: 2013,
    position: 'Ala-pivô',
    height: '1,98',
    championship: 0,
    description: 'Reggie Bullock é um jogador norte-americano de basquete profissional que atualmente joga pelo Dallas Mavericks da National Basketball Association. Ele jogou basquete universitário na Carolina do Norte antes de ser selecionado pelo Los Angeles Clippers na primeira rodada do Draft da NBA de 2013.',
    img: 'https://tarheeltribune.files.wordpress.com/2023/01/bullock-portland.png'
  },
  {
    name: 'Zach Randolph',
    mvp: 0,
    jersey_number: 50,
    finals_mvp: 0,
    age: 41,
    born: '16/07/1981',
    current_team: 'Memphis Grizzlies',
    draft_team: 'Portland Trail Blazzers',
    nacionality: 'EUA',
    draft_position: '19º',
    draft_year: 2001,
    position: 'Ala-pivô',
    height: '2,06',
    championship: 0,
    description: 'Zachary "Zach" Randolph, é um ex-jogador de basquete norte-americano',
    img: 'https://static01.nyt.com/images/2017/08/11/sports/11randolph/11randolph-superJumbo-v2.jpg'
  },
  {
    name: 'Pau Gasol',
    mvp: 0,
    jersey_number: 16,
    finals_mvp: 0,
    age: 42,
    born: '06/07/1980',
    current_team: 'Milwaukee Bucks',
    draft_team: 'Memphis Grizzlies',
    nacionality: 'Espanha',
    draft_position: '3º',
    draft_year: 2001,
    position: 'Ala-pivô',
    height: '2,16',
    championship: 2,
    description: 'Pau Gasol Sáez é um ex-jogador espanhol de basquete profissional. Ele foi seis vezes selecionado para o All-Star Game e ganhou dois títulos da NBA com o Los Angeles Lakers em 2009 e 2010. Ele foi o Novato do Ano em 2002 com o Memphis Grizzlies, sendo o primeiro jogador não americano a ganhar esse prêmio.',
    img: 'https://ktla.com/wp-content/uploads/sites/4/2022/11/GettyImages-464682477.jpeg'
  },
  {
    name: 'Mark Gasol',
    mvp: 0,
    jersey_number: 33,
    finals_mvp: 0,
    age: 38,
    born: '29/01/1985',
    current_team: 'Milwaukee Bucks',
    draft_team: 'Los Angeles Lakers',
    nacionality: 'Espanha',
    draft_position: '48º',
    draft_year: 2007,
    position: 'Ala-pivô',
    height: '2,11',
    championship: 0,
    description: 'Marc Gasol Sáez é um jogador de basquete profissional espanhol que joga no Bàsquet Girona da Liga Espanhola. Ele foi selecionado pelo Los Angeles Lakers com a 48ª escolha geral no Draft da NBA de 2007 da National Basketball Association.',
    img: 'https://images2.minutemediacdn.com/image/fetch/c_fill,g_auto,f_auto,h_1222,w_1600/https%3A%2F%2Fbealestreetbears.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F07%2F899798084.jpeg'
  },
  {
    name: 'Anderson Varejão',
    mvp: 0,
    jersey_number: 17,
    finals_mvp: 0,
    age: 40,
    born: '28/09/1982',
    current_team: 'Golden State Warriors',
    draft_team: 'Orlando Magic',
    nacionality: 'Brasil',
    draft_position: '30º',
    draft_year: 2004,
    position: 'Ala-pivô',
    height: '2,11',
    championship: 1,
    description: 'Anderson Varejão, mais conhecido como Varejão ou Andy, é um ex-jogador brasileiro de basquetebol profissional. Com 2,11 metros de altura, ele atuava como pivô. Atualmente é embaixador global e consultor de desenvolvimento de atletas do Cleveland Cavaliers.',
    img: 'https://images2.minutemediacdn.com/image/fetch/c_fill,g_auto,f_auto,h_1222,w_1600/https%3A%2F%2Fbealestreetbears.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F07%2F899798084.jpeg'
  },
  {
    name: 'Gordon Hayward',
    mvp: 0,
    jersey_number: 20,
    finals_mvp: 0,
    age: 33,
    born: '23/04/1990',
    current_team: 'Charlote Hornets',
    draft_team: 'Utah Jazz',
    nacionality: 'EUA',
    draft_position: '9º',
    draft_year: 2011,
    position: 'Ala-armador',
    height: '1,98',
    championship: 0,
    description: 'Gordon Daniel Hayward é um jogador norte-americano profissional de basquete que atualmente joga no Charlotte Hornets da National Basketball Association. Ele jogou duas temporadas de basquete universitário na Universidade Butler e foi selecionado pelo Utah Jazz como a nona escolha geral no Draft da NBA de 2010.',
    img: 'https://swarmandsting.com/wp-content/uploads/getty-images/2018/08/1309417342.jpeg'
  },
  {
    name: 'Dirk Nowitzki',
    mvp: 1,
    jersey_number: 41,
    finals_mvp: 1,
    age: 44,
    born: '19/06/1978',
    current_team: 'Dallas Mavericks',
    draft_team: 'Milwaukee Bucks',
    nacionality: 'EUA',
    draft_position: '9º',
    draft_year: 1998,
    position: 'Ala-pivô',
    height: '2,13',
    championship: 1,
    description: 'Dirk Werner Nowitzki é um ex-basquetebolista alemão que atuava como como ala-pivô. Com 2,13 metros de altura, Nowitzki atuou durante toda a sua carreira pela equipe do Dallas Mavericks, da NBA.',
    img: 'https://static.dw.com/image/48269678_605.jpg'
  },
  {
    name: 'John Stokton',
    mvp: 0,
    jersey_number: 12,
    finals_mvp: 0,
    age: 61,
    born: '26/04/1961',
    current_team: 'Utah Jazz',
    draft_team: 'Utah Jazz',
    nacionality: 'EUA',
    draft_position: '16º',
    draft_year: 1984,
    position: 'Armador',
    height: '1,85',
    championship: 0,
    description: 'John Houston Stockton é um ex-basquetebolista norte-americano que dispendeu toda a sua carreira como armador do Utah Jazz na National Basketball Association. Stockton é considerado um dos maiores armadores da história do esporte, detendo o recorde da NBA de mais assistências e roubadas de bola por largas vantagens.',
    img: 'https://vault.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY5MDk4NDgyNDA5NDE2MTU1/john-stockton-1986jpg.jpg'
  },
  {
    name: 'Hakeem Olajuwon',
    mvp: 0,
    jersey_number: 34,
    finals_mvp: 2,
    age: 60,
    born: '21/01/1963',
    current_team: 'Toronto Raptors',
    draft_team: 'Houston Rockets',
    nacionality: 'Nigéria',
    draft_position: '1º',
    draft_year: 1984,
    position: 'Ala-pivô',
    height: '2,13',
    championship: 2,
    description: 'Hakeem Abdul "The Dream" Olajuwon é um ex-jogador nigeriano-americano de basquete que atuou pela National Basketball Association. ',
    img: 'https://www.basketballnetwork.net/.image/c_fit%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1280/MTkyOTUzODU2NTg4NTIyNzE3/hakeem-olajuwon.jpg'
  },
  {
    name: 'Kareem Abdul-Jabbar',
    mvp: 6,
    jersey_number: 34,
    finals_mvp: 2,
    age: 76,
    born: '16/04/1947',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Milwaukee Bucks',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 1969,
    position: 'Pivô',
    height: '2,19',
    championship: 4,
    description: 'Kareem Abdul-Jabbar - em árabe, كريم عبد الجبار -, nascido Ferdinand Lewis "Lew" Alcindor Jr., é um ex-basquetebolista que atuava como pivô, amplamente considerado como um dos maiores jogadores da história do basquete americano.',
    img: 'https://www.gannett-cdn.com/authoring/2017/05/04/NFDD/ghows-FD-4dec8d23-c3ef-3c38-e053-0100007f8127-2cde7895.jpeg'
  },
  {
    name: 'Wilt Chamberlaim',
    mvp: 4,
    jersey_number: 13,
    finals_mvp: 1,
    age: 'Falecimento em 12/10/1999',
    born: '21/08/1936',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Golden State Warriors',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 1969,
    position: 'Pivô',
    height: '2,19',
    championship: 2,
    description: 'Wilton Norman Chamberlain foi um jogador de basquete americano que jogou como pivô e é considerado um dos maiores jogadores da história. Ele jogou no Philadelphia/San Francisco Warriors, Philadelphia 76ers e o Los Angeles Lakers da National Basketball Association.',
    img: 'https://www.nydailynews.com/resizer/lHGw3WXUNXewvZ-i_L6xMo1vpXs=/1200x0/filters:format(jpg):quality(70)/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/DJZYV34UFTSQXTE5GVX5R6TWSY.jpg'
  },
  {
    name: 'Donovan Mitchell',
    mvp: 0,
    jersey_number: 45,
    finals_mvp: 0,
    age: 26,
    born: '07/09/1996',
    current_team: 'Cleveland Cavaliers',
    draft_team: 'Utah Jazz',
    nacionality: 'EUA',
    draft_position: '13º',
    draft_year: 2017,
    position: 'Armador',
    height: '1,85',
    championship: 0,
    description: 'Donovan Mitchell Jr. é um jogador norte-americano de basquete profissional que atualmente joga no Cleveland Cavaliers da National Basketball Association.',
    img: 'https://pbs.twimg.com/media/FlhB98YWYAA0S_i.jpg:large'
  },
  {
    name: 'Rudy Gobert',
    mvp: 0,
    jersey_number: 27,
    finals_mvp: 0,
    age: 30,
    born: '26/06/1992',
    current_team: 'Minnesota Timberwolves',
    draft_team: 'Denver Nuggets',
    nacionality: 'EUA',
    draft_position: '27º',
    draft_year: 2013,
    position: 'Pivô',
    height: '2,16',
    championship: 0,
    description: 'Rudy Gobert-Bourgarel é um basquetebolista profissional francês que atualmente joga pelo Minnesota Timberwolves na NBA. Atua também pela Seleção Francesa com a qual conquistou a medalha de bronze no Mundial de 2014. Possui 2,16 m de altura e atua na posição pivô',
    img: 'https://cdn.nba.com/manage/2023/04/rudy-gobert-iso-looks.jpg'
  },
  {
    name: 'Damian Lillard',
    mvp: 0,
    jersey_number: 0,
    finals_mvp: 0,
    age: 32,
    born: '15/07/1990',
    current_team: 'Portland Trail Blazers',
    draft_team: 'Portland Trail Blazers',
    nacionality: 'EUA',
    draft_position: '6º',
    draft_year: 2012,
    position: 'Armador',
    height: '1,88',
    championship: 0,
    description: 'Damian Lamonte Ollie Lillard Sr. é um jogador de basquete norte-americano e rapper que atua como armador pelo Portland Trail Blazers na National Basketball Association.',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Damian_Lillard_%2851658684394%29.jpg/1200px-Damian_Lillard_%2851658684394%29.jpg'
  },
  {
    name: 'Jordan Clarkson',
    mvp: 0,
    jersey_number: 0,
    finals_mvp: 0,
    age: 30,
    born: '07/06/1992',
    current_team: 'Utah Jazz',
    draft_team: 'Washington Wizards',
    nacionality: 'EUA',
    draft_position: '46º',
    draft_year: 2014,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Jordan Taylor Clarkson é um jogador de basquete profissional filipino-americano do Utah Jazz da National Basketball Association. Ele jogou basquete universitário por duas temporadas na Universidade de Tulsa antes de se transferir para a Universidade do Missouri.',
    img: 'https://cdn.vox-cdn.com/thumbor/VQfu6lST7pHR8_C_p6T21DOwprc=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/24344118/1450731520.jpg'
  },
  {
    name: 'Jimmy Butler',
    mvp: 0,
    jersey_number: 22,
    finals_mvp: 0,
    age: 33,
    born: '14/09/1989',
    current_team: 'Miami Heat',
    draft_team: 'Washington Wizards',
    nacionality: 'EUA',
    draft_position: '30º',
    draft_year: 2011,
    position: 'Ala-pivô',
    height: '2.01',
    championship: 0,
    description: 'Jimmy Butler III é um jogador norte-americano de basquete profissional que atualmente joga no Miami Heat da National Basketball Association. Butler foi selecionado pelo Chicago Bulls como a 30ª escolha geral no draft da NBA de 2011. Em 2015, ele foi o vencedor do Prêmio de Jogador que Mais Evoluiu.',
    img: 'https://r8p9h9p8.rocketcdn.me/wp-content/uploads/2023/04/Jimmy-Butler-2-e1682400583260.jpg'
  },
  {
    name: 'Bam Adebayo',
    mvp: 0,
    jersey_number: 13,
    finals_mvp: 0,
    age: 25,
    born: '18/07/1997',
    current_team: 'Miami Heat',
    draft_team: 'Miami Heat',
    nacionality: 'EUA',
    draft_position: '14º',
    draft_year: 2017,
    position: 'Ala-pivô',
    height: '2.17',
    championship: 0,
    description: 'Edrice Femi "Bam" Adebayo é um jogador norte-americano profissional de basquete que joga atualmente no Miami Heat da National Basketball Association. Ele jogou basquete universitário na Universidade de Kentucky antes de ser selecionado pelo Heat como a 14ª escolha geral no Draft da NBA de 2017.',
    img: 'https://jornalesportes.com/wp-content/uploads/2020/11/50594023591_b45dbfc128_c-800x397-20.jpg'
  },
  {
    name: 'Tyler Herro',
    mvp: 0,
    jersey_number: 14,
    finals_mvp: 0,
    age: 23,
    born: '20/01/2000',
    current_team: 'Miami Heat',
    draft_team: 'Miami Heat',
    nacionality: 'EUA',
    draft_position: '13º',
    draft_year: 2019,
    position: 'Ala',
    height: '1,96',
    championship: 0,
    description: 'Tyler Christopher Herro é um jogador norte-americano de basquete profissional que atualmente joga pelo Miami Heat na National Basketball Association. Ele jogou basquete universitário na Universidade de Kentucky e foi selecionado pelo Heat como a 13ª escolha geral no Draft da NBA de 2019',
    img: 'https://pbs.twimg.com/media/Ft3xdv5X0AET1lw.jpg:large'
  },
  {
    name: 'Kyle Lowry',
    mvp: 0,
    jersey_number: 7,
    finals_mvp: 0,
    age: 37,
    born: '25/03/1986',
    current_team: 'Miami Heat',
    draft_team: 'Miami Heat',
    nacionality: 'EUA',
    draft_position: '13º',
    draft_year: 2006,
    position: 'Armador',
    height: '1,83',
    championship: 1,
    description: 'Kyle Terrell Lowry é um jogador norte-americano profissional de basquete que atualmente joga no Miami Heat da National Basketball Association. Com o Toronto Raptors, ele foi selecionado seis vezes para o All-Star Game e venceu o título da NBA em 2019, o primeiro título na história da franquia.',
    img: 'https://images2.minutemediacdn.com/image/fetch/w_736,h_485,c_fill,g_auto,f_auto/https%3A%2F%2Fsircharlesincharge.com%2Fwp-content%2Fuploads%2Fimagn-images%2F2017%2F07%2F18391042-850x560.jpeg'
  },
  {
    name: 'Larry Bird',
    mvp: 3,
    jersey_number: 33,
    finals_mvp: 2,
    age: 37,
    born: '07/12/1956',
    current_team: 'Boston Celtics',
    draft_team: 'Boston Celtics',
    nacionality: 'EUA',
    draft_position: '6º',
    draft_year: 1978,
    position: 'Ala-pivô',
    height: '2,06',
    championship: 3,
    description: 'Larry Joe Bird é um ex-jogador, treinador e executivo de basquetebol da National Basketball Association norte-americano.',
    img: 'https://cdn.nba.com/manage/2019/03/Larry_Bird_Emotion_ISO.jpg'
  },
  {
    name: 'Oscar Robertson',
    mvp: 0,
    jersey_number: 33,
    finals_mvp: 0,
    age: 84,
    born: '24/11/1938',
    current_team: 'Milwaukee Bucks',
    draft_team: 'Cincinnati Royals (Atual Sacramento Kings)',
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 1960,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Oscar Palmer Robertson, apelidado de "The Big O", é um ex-jogador de basquete profissional que jogou pelo Cincinnati Royals e pelo Milwaukee Bucks na National Basketball Association. Robertson jogou como armador e foi 12 vezes All-Star, 11 vezes membro da Equipe All-NBA e venceu o Prêmio de MVP.',
    img: 'https://cdn.nba.com/manage/2021/08/oscar-robertson-dribble-1920.jpg'
  },
  {
    name: 'Jayson Tatum',
    mvp: 0,
    jersey_number: 0,
    finals_mvp: 0,
    age: 25,
    born: '03/03/1998',
    current_team: 'Boston Celtics',
    draft_team: 'Boston Celtics',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 2017,
    position: 'Ala',
    height: '2,03',
    championship: 0,
    description: 'Jayson Christopher Tatum é um norte-americano profissional que atualmente joga pelo Boston Celtics na National Basketball Association. Depois de uma temporada em Duke, ele entrou no Draft da NBA de 2017 e foi selecionado na terceira escolha geral pelo Boston Celtics.',
    img: 'https://tntsports.com.br/__export/1640041193664/sites/esporteinterativo/img/2021/12/20/jayson_tatum_1.jpg'
  },
  {
    name: 'Jaylen Brown',
    mvp: 0,
    jersey_number: 7,
    finals_mvp: 0,
    age: 26,
    born: '24/10/1996',
    current_team: 'Boston Celtics',
    draft_team: 'Boston Celtics',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 2016,
    position: 'Ala-armador',
    height: '1,98',
    championship: 0,
    description: 'Jaylen Marselles Brown é um basquetebolista norte-americano que atua como ala-armador ou ala. Atualmente joga no Boston Celtics, da National Basketball Association. Ele jogou um ano de basquete universitário na Universidade da Califórnia, sendo nomeado pro Primeiro-Time da Pac-12 e Novato do Ano da Pac-12.',
    img: 'https://www.nbcsports.com/sites/rsnunited/files/article/hero/Jaylen-Brown-GettyImages-1240055870.jpg'
  },
  {
    name: 'Marcus Smart',
    mvp: 0,
    jersey_number: 36,
    finals_mvp: 0,
    age: 29,
    born: '06/03/1994',
    current_team: 'Boston Celtics',
    draft_team: 'Boston Celtics',
    nacionality: 'EUA',
    draft_position: '6º',
    draft_year: 2014,
    position: 'Armador',
    height: '1,91',
    championship: 0,
    description: 'Marcus Osmond Smart é um americano jogador profissional de basquete que joga no Boston Celtics da National Basketball Association. Ele jogou basquete universitário na Universidade de Oklahoma antes de ser selecionado pelo Celtics com a sexta escolha geral no Draft da NBA de 2014.',
    img: 'https://media.necn.com/sites/49/2023/03/Smart_Marcus_AP_20061581920424_0.jpg?quality=85&strip=all'
  },
  {
    name: 'Al Horford',
    mvp: 0,
    jersey_number: 42,
    finals_mvp: 0,
    age: 36,
    born: '03/06/1986',
    current_team: 'Boston Celtics',
    draft_team: 'Atlanta Hawks',
    nacionality: 'Republica Dominicana',
    draft_position: '3º',
    draft_year: 2007,
    position: 'Ala-pivô',
    height: '2,06',
    championship: 0,
    description: 'Alfred "Al" Joel Horford Reynoso é um jogador dominicano de basquete profissional que atualmente joga no Boston Celtics da National Basketball Association. Horford jogou três anos no basquete universitário na Universidade da Flórida, onde, liderou a equipe a dois títulos do Torneio da NCAA em 2006 e 2007.',
    img: 'https://www.nbcsports.com/sites/rsnunited/files/article/hero/Al-Horford-USATSI_18513457.jpg'
  },
  {
    name: 'Derrick White',
    mvp: 0,
    jersey_number: 9,
    finals_mvp: 0,
    age: 28,
    born: '02/07/1994',
    current_team: 'Boston Celtics',
    draft_team: 'San Antonio Spurs',
    nacionality: 'EUA',
    draft_position: '29º',
    draft_year: 2017,
    position: 'Armador',
    height: '1,93',
    championship: 0,
    description: 'Derrick White é um jogador norte-americano de basquete profissional que atualmente joga no Boston Celtics da National Basketball Association.',
    img: 'https://fivethirtyeight.com/wp-content/uploads/2023/02/GettyImages-1456939824-4x3-1.jpg?w=916'
  },
  {
    name: 'Malcolm Brogdon',
    mvp: 0,
    jersey_number: 13,
    finals_mvp: 0,
    age: 30,
    born: '11/12/1992',
    current_team: 'Boston Celtics',
    draft_team: 'Milwaukee Bucks',
    nacionality: 'EUA',
    draft_position: '36º',
    draft_year: 2016,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Malcolm Moses Adams Brogdon é um jogador norte-americano de basquete profissional que atualmente joga pelo Boston Celtics da National Basketball Association. Ele jogou pela Universidade da Virgínia e foi selecionado pelo Milwaukee Bucks como a 36° escolha geral no Draft da',
    img: 'https://www.masslive.com/resizer/Bn79ZOwjKSgnYgn2N_xepHUy9eE=/1280x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/GQ4WCXRLG5AMREH2CHGGBE4RTQ.jpg'
  },
  {
    name: 'Spencer Dinwiddie',
    mvp: 0,
    jersey_number: 26,
    finals_mvp: 0,
    age: 30,
    born: '06/04/1993',
    current_team: 'Brooklyn Nets',
    draft_team: 'Detroit Pistons',
    nacionality: 'EUA',
    draft_position: '38º',
    draft_year: 2014,
    position: 'Armador',
    height: '1,96',
    championship: 0,
    description: 'Spencer Gray Dinwiddie é um jogador norte-americano de basquete profissional que atualmente joga no Brooklyn Nets da National Basketball Association. Ele jogou basquete universitário na Universidade do Colorado e foi selecionado pelo Detroit Pistons na segunda rodada do Draft da NBA de 2014.',
    img: 'https://nypost.com/wp-content/uploads/sites/2/2023/03/NYPICHPDPICT000007859667.jpg'
  },
  {
    name: 'Jerry West',
    mvp: 0,
    jersey_number: 44,
    finals_mvp: 1,
    age: 84,
    born: '28/05/1938',
    current_team: 'Los Angeles Lakers',
    draft_team: 'Minneapolis Lakers (Atual Los Angeles Lakers)',
    nacionality: 'EUA',
    draft_position: '2º',
    draft_year: 1960,
    position: 'Armador',
    height: '1,91',
    championship: 1,
    description: 'Jerome Alan West é um ex-jogador de basquetebol norte-americano que atualmente exerce a função de Conselheiro nos Clippers. West ganhou notoriedade por ter servido de inspiração para o desenho do logotipo da NBA, o qual é baseado na imagem de uma jogada de Jerry West.',
    img: 'https://www.si.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY4MDMxMzY1ODQwMzgxMzEy/jerry-west-main-marqueejpg.jpg'
  },
  {
    name: 'Dennis Rodman',
    mvp: 0,
    jersey_number: 91,
    finals_mvp: 0,
    age: 84,
    born: '13/05/1961',
    current_team: 'Chicago Bulls',
    draft_team: 'Detroit Pistons',
    nacionality: 'EUA',
    draft_position: '3º',
    draft_year: 1986,
    position: 'Ala-pivô',
    height: '2,01',
    championship: 5,
    description: 'Dennis Keith Rodman, é um ex-jogador de basquetebol profissional norte-americano e atual integrante do Hall da Fama do basquetebol, um dos melhores no setor defensivo e no rebote. Apelidado de "the worm", o verme, por sua feroz habilidade de posicionamento e rebote para um jogador relativamente baixo para a posição',
    img: 'https://s2.glbimg.com/xvPL5LPcOpeX7ztY7cYJaY5T8ms=/1200x/smart/filters:cover():strip_icc()/s.glbimg.com/es/ge/f/original/2013/11/03/dennisrodman_get3.jpg'
  },
  {
    name: 'Scottie Pippen',
    mvp: 0,
    jersey_number: 33,
    finals_mvp: 0,
    age: 57,
    born: '25/09/1965',
    current_team: 'Chicago Bulls',
    draft_team: 'Chicago Bulls',  
    nacionality: 'EUA',
    draft_position: '5º',
    draft_year: 1987,
    position: 'Ala',
    height: '2,03',
    championship: 6,
    description: 'Scotty Scottie Maurice Pippen é um ex-basquetebolista estadunidense que atuava como ala. Ele jogou 17 temporadas na National Basketball Association, vencendo seis títulos da NBA com o Chicago Bulls.',
    img: 'https://cdn.nba.com/teams/legacy/www.nba.com/bulls/sites/bulls/files/200511_pippen_cp.jpg'
  },
  {
    name: 'Devin Booker',
    mvp: 0,
    jersey_number: 1,
    finals_mvp: 0,
    age: 26,
    born: '30/10/1996',
    current_team: 'Phoenix Suns',
    draft_team: 'Phoenix Suns',  
    nacionality: 'EUA',
    draft_position: '13º',
    draft_year: 2015,
    position: 'Ala',
    height: '1,96',
    championship: 0,
    description: 'Devin Armani Booker, é um basquetebolista profissional norte-americano que atualmente joga pelo Phoenix Suns na National Basketball Association. Tem 1,96 m de altura e atua como ala-armador. Booker jogou uma temporada de basquete universitário pelos Wildcats da Universidade de Kentucky.',
    img: 'https://r8p9h9p8.rocketcdn.me/wp-content/uploads/2023/04/Devin-Booker-1.jpg'
  },
  {
    name: 'Deandre Ayton',
    mvp: 0,
    jersey_number: 22,
    finals_mvp: 0,
    age: 24,
    born: '23/07/1998',
    current_team: 'Phoenix Suns',
    draft_team: 'Phoenix Suns',  
    nacionality: 'Bahamas',
    draft_position: '1º',
    draft_year: 2018,
    position: 'Pivô',
    height: '2,13',
    championship: 0,
    description: 'Deandre Edoneille Ayton é um basquetebolista bahamense que atua como pivô. Atualmente defende o Phoenix Suns na NBA. Ele foi um dos melhores no basquete universitário na temporada de 2017–18. Em janeiro de 2017, Ayton foi selecionado para jogar o McDonald s All-American Game.',
    img: 'https://cdn.vox-cdn.com/thumbor/_fnKFL8p-n1z-uspXVxRGGlRDZc=/0x492:5184x3456/1400x933/filters:focal(2140x850:2968x1678):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/69509714/1233677064.0.jpg'
  },
  {
    name: 'Karl Anthony Towns',
    mvp: 0,
    jersey_number: 32,
    finals_mvp: 0,
    age: 27,
    born: '15/11/1995',
    current_team: 'Minnesota Timberwolves',
    draft_team: 'Minnesota Timberwolves',  
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 2018,
    position: 'Pivô',
    height: '2,13',
    championship: 0,
    description: 'Karl-Anthony Towns Jr. é um jogador dominicano-americano de basquete profissional que atualmente joga no Minnesota Timberwolves da National Basketball Association.',
    img: 'https://s2.glbimg.com/sIuGBBK98S9LM78SCftoYx-HiNA=/620x480/smart/e.glbimg.com/og/ed/f/original/2022/04/13/anthony_towns.jpg'
  },
  {
    name: 'Anthony Edwards',
    mvp: 0,
    jersey_number: 1,
    finals_mvp: 0,
    age: 21,
    born: '05/08/2001',
    current_team: 'Minnesota Timberwolves',
    draft_team: 'Minnesota Timberwolves',  
    nacionality: 'EUA',
    draft_position: '1º',
    draft_year: 2020,
    position: 'Ala',
    height: '1,93',
    championship: 0,
    description: 'Anthony DeVante Edwards é um jogador norte-americano de basquete profissional que atualmente joga no Minnesota Timberwolves da National Basketball Association. Ele jogou basquete universitário pela Universidade da Geórgia e foi selecionado pelos Timberwolves como a primeira escolha geral no draft da NBA de 2020.',
    img: 'https://www.twincities.com/wp-content/uploads/2023/04/AP23110179789920.jpg?w=552'
  },
  {
    name: 'Nikola Jokic',
    mvp: 2,
    jersey_number: 15,
    finals_mvp: 0,
    age: 28,
    born: '19/02/1995',
    current_team: 'Denver Nuggets',
    draft_team: 'Denver Nuggets',  
    nacionality: 'Sérvia',
    draft_position: '41º',
    draft_year: 2014,
    position: 'Pivô',
    height: '2,11',
    championship: 0,
    description: 'Nikola Jokić é um jogador de basquete profissional que atualmente joga no Denver Nuggets da National Basketball Association. Ele recebeu o apelido de "The Joker". Quatro vezes selecionado para o All-Star Game, ele ganhou o prêmio de MVP da NBA nas temporadas de 2020-21 e 2021-22.',
    img: 'https://r8p9h9p8.rocketcdn.me/wp-content/uploads/2023/03/063_1247422673.jpg'
  },
  {
    name: 'Aaron Gordon',
    mvp: 0,
    jersey_number: 50,
    finals_mvp: 0,
    age: 27,
    born: '16/09/1995',
    current_team: 'Denver Nuggets',
    draft_team: 'Orlando Magic',  
    nacionality: 'EUA',
    draft_position: '4º',
    draft_year: 2014,
    position: 'Ala',
    height: '2,13',
    championship: 0,
    description: 'Aaron Addison Gordon é um jogador norte-americano de basquete profissional que atualmente joga pelo Denver Nuggets, disputando a National Basketball Association. Ele jogou basquete universitário pela Universidade do Arizona e foi selecionado pelo Orlando Magic como a quarta escolha geral no draft da NBA de 2014',
    img: 'https://nugglove.com/wp-content/uploads/getty-images/2017/07/1433709116.jpeg'
  },
  {
    name: 'Jamal Murray',
    mvp: 0,
    jersey_number: 27,
    finals_mvp: 0,
    age: 26,
    born: '23/02/1997',
    current_team: 'Denver Nuggets',
    draft_team: 'Denver Nuggets',  
    nacionality: 'Canadá',
    draft_position: '7º',
    draft_year: 2016,
    position: 'Armador',
    height: '1,93',
    championship: 0,
    description: 'Jamal Murray é um jogador canadense de basquete profissional que atualmente joga pelo Denver Nuggets da National Basketball Association. Ele jogou basquete universitário pela Universidade de Kentucky e foi selecionado pelos Nuggets como a 7º escolha geral do draft da NBA de 2016. ',
    img: 'https://www.denverpost.com/wp-content/uploads/2023/03/TDP-L-NUGGETS-BULLS_AAO7620xx.jpg?w=525'
  },
]
